### ISSUE TITLE
Build process of the MIV model fails

### ISSUE THREAD

**Issue by BjoernPK** [DLR-TS/sumo-scenarios#2]
Dear community,

unfortunately, in the repository checked out yesterday, the execution of the `build.sh` file from the `brunswick/miv` directory completes with errors. Please note the log file attached to this issue.

Is this a known (or maybe local) error? What can I do to fix the error?

Many thank for your support in advance!

Best regards,
Björn

[miv.log](https://github.com/DLR-TS/sumo-scenarios/files/7265583/miv.log)

**Comment by namdre** [comment]
The build files were recently adapted to work with the latest development version of netconvert. Either
- updated netconvert (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version)
- try building scenario version 10401ab8dd83029f3ec246e439f6ab465553b9ec

**Comment by BjoernPK** [comment]
Thanks for the quick and helpful reply! With the new netconvert version installed the build process works like a charm! :)
